import { useEffect, useMemo, useState } from 'react';
import type { Form, SubmissionValue } from '../types/form.types';
import type { GameProfile, ProfileTestData } from '../types/game-profile.types';
import { gameProfileApi } from '../services/api';
import { FormField } from './FormField';

const empty: ProfileTestData = { teamNumber: '', forms: {}, metrics: {} };

export const PreviewTestData: React.FC<{ profile: GameProfile; editable: boolean; forms: Form[] }> = ({ profile, editable, forms }) => {
  const [open, setOpen] = useState(false);
  const [data, setData] = useState<ProfileTestData>(empty);
  const [formId, setFormId] = useState('');
  const [message, setMessage] = useState('');
  useEffect(() => { void gameProfileApi.getTestData(profile.id).then(setData).catch(() => setData(empty)); }, [profile.id]);
  const activeForm = useMemo(() => forms.find((form) => form.id === formId) || null, [forms, formId]);
  const save = async () => { try { await gameProfileApi.setTestData(profile.id, data); setMessage('Test data saved. It is isolated from submissions and deleted when published.'); } catch (error) { setMessage((error as Error).message || 'Unable to save test data.'); } };
  return <><button type="button" disabled={!editable} onClick={() => setOpen(true)} className="rounded border border-blue-200 bg-blue-50 px-3 py-2 text-sm font-bold text-blue-700 disabled:opacity-50">Submit Test Data</button>{open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 p-4" onClick={() => setOpen(false)}><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-white p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><h3 className="text-lg font-bold text-gray-900">Submit Test Data</h3><p className="mt-1 text-sm text-gray-500">This data is only used by profile preview and never becomes a real submission.</p></div><button type="button" onClick={() => setOpen(false)} className="rounded px-2 py-1 text-sm font-bold text-gray-500 hover:bg-gray-100">Close</button></div><label className="mt-4 block text-sm font-medium">Team number<input value={data.teamNumber} disabled={!editable} onChange={(event) => setData({ ...data, teamNumber: event.target.value })} className="mt-1 w-full rounded border px-3 py-2" /></label>{forms.length > 0 && <><select value={formId} onChange={(event) => setFormId(event.target.value)} className="mt-4 rounded border px-3 py-2 text-sm"><option value="">Choose a form</option>{forms.map((form) => <option key={form.id} value={form.id}>{form.name}</option>)}</select>{activeForm?.fields.map((field) => <div key={field.id} className="mt-3"><label className="mb-1 block text-sm font-medium">{field.label}</label><FormField field={field} value={data.forms[activeForm.id]?.[String(field.id)] as SubmissionValue} onChange={(value) => setData({ ...data, forms: { ...data.forms, [activeForm.id]: { ...data.forms[activeForm.id], [String(field.id)]: value } } })} /></div>)}</>}{profile.configuration.metrics.filter((metric) => metric.source !== 'scout').map((metric) => <label key={metric.id} className="mt-3 block text-sm font-medium">{metric.label}<input value={String(data.metrics[metric.id] || '')} disabled={!editable} onChange={(event) => setData({ ...data, metrics: { ...data.metrics, [metric.id]: event.target.value } })} className="mt-1 w-full rounded border px-3 py-2" /></label>)}<div className="mt-5 flex items-center gap-3"><button type="button" disabled={!editable} onClick={() => void save()} className="rounded bg-blue-600 px-3 py-2 text-sm font-bold text-white disabled:opacity-50">Save Test Data</button>{message && <p role="status" className="text-sm text-gray-600">{message}</p>}</div></div></div>}</>;
};
